# Generated by Django 3.1.1 on 2020-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('bnum', models.IntegerField(primary_key=True, serialize=False)),
                ('intro', models.TextField()),
                ('url', models.TextField(max_length=200)),
                ('date', models.DateTimeField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
