# Generated by Django 3.1.1 on 2020-10-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_stylekind'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_brand_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('b_num', models.IntegerField()),
            ],
        ),
    ]
