# Generated by Django 3.1.1 on 2020-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
