# Generated by Django 3.1.1 on 2020-10-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_stylekind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.TextField(max_length=250),
        ),
    ]
