# Generated by Django 3.1.1 on 2020-10-25 09:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_user_brand_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yvideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
