# Generated by Django 3.1.1 on 2020-10-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20201022_2251'),
        ('brand', '0006_yvideo'),
    ]

    operations = [
    ]
